defaults:
  - _self_
  # - slurm
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

hydra.job.chdir: False

data-generation:
  run_type : "smac"
  max_hp_comb: 1
  n_samples_spacing: [20]
  n_samples : 20
  init_design_max_ratio: 0.25
  init_design_n_configs_per_hyperparamter: 8
  n_optimized_params: 2
  n_seeds: 5


hydra:
  run:
    dir: "."